name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
      
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER_NAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY_PRIVATE }}
        script: |
          cd ~/Desktop/webdev_projects/binasbobablog2/
          git pull origin main
          docker compose down
          docker compose build
          docker compose up
